all:
  hosts:
    node1:
      ansible_host: 172.16.35.10
      ip: 172.16.35.10
    node2:
      ansible_host: 172.16.35.11
      ip: 172.16.35.11
    node3:
      ansible_host: 172.16.35.12
      ip: 172.16.35.12
  children:
    kube_control_plane:
      hosts:
        node1:
    kube_node:
      hosts:
        node2:
        node3:
    etcd:
      hosts:
        node1:
      k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
