all:
  hosts:
    node1:
      ansible_host: 172.18.8.10
      ip: 172.18.8.10
    node2:
      ansible_host: 172.18.8.11
      ip: 172.18.8.11
    node3:
      ansible_host: 172.18.8.12
      ip: 172.18.8.12
    node4:
      ansible_host: 172.18.8.13
      ip: 172.18.8.13
  children:
    kube_control_plane:
      hosts:
        node1:
    kube_node:
      hosts:
        node2:
        node3:
        node4:
    etcd:
      hosts:
        node1:
    nfs_storage:
      hosts:
        node4:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
        nfs_storage:
    calico_rr:
      hosts: {}
