- name: Initial provisioning
  hosts: all
  tasks:
    - name: Get the list of hosts from the inventory
      add_host:
        name: "{{ item }}"
        groups: hosts_to_add
        ansible_host: "{{ hostvars[item]['ansible_host'] }}"
      with_inventory_hostnames:
        - all

    - name: Add hosts to /etc/hosts
      become: true
      lineinfile:
        path: /etc/hosts
        line: "{{ hostvars[item]['ansible_host'] }} {{ item }}"
        state: present
      with_items: "{{ groups['hosts_to_add'] }}"

    - name: Check if firewalld is installed
      become: true
      shell: |
        systemctl is-active --quiet firewalld && echo "Firewalld is running"
      register: firewalld_status
      ignore_errors: true
    
    - name: Stop and disable firewalld if it is installed
      become: true
      systemd:
        name: firewalld
        state: stopped
        enabled: false
      when: firewalld_status.rc == 0

    - name: Update packages (apt)
      become: true
      apt:
        update_cache: yes
        upgrade: yes
      when: ansible_pkg_mgr == 'apt'

    - name: Update packages (yum)
      become: true
      yum:
        name: '*'
        state: latest
      when: ansible_pkg_mgr == 'yum'

    - name: Install required packages (apt)
      become: true
      apt:
        name: nfs-common, mc
        state: latest
      when: ansible_pkg_mgr == 'apt'

    - name: Install required packages (yum)
      become: true
      yum:
        name: nfs-utils, mc
        state: latest
      when: ansible_pkg_mgr == 'yum'